const fs = require('fs');

let content = fs.readFileSync('src/SalesPage.tsx', 'utf8');

// 2. Transmissão ao vivo: https://pay.kiwify.com.br/elj3ZQY
// Update card 2:
const card2Old = `{/* 2. Transmissão ao vivo */}            <div className="p-6 rounded-2xl bg-gray-50 border border-gray-200 shadow-xl flex flex-col justify-between">              <div>                <h3 className="text-lg font-black text-black uppercase tracking-tight mb-2">Transmissão ao Vivo</h3>                <p className="text-black text-sm mb-4 font-medium">Estrutura de streaming para seu evento ou podcast.</p>              </div>              <a href="https://wa.me/5549991052315?text=Ol%C3%A1%21%20Gostaria%20de%20saber%20mais%20sobre%20Transmiss%C3%A3o%20ao%20Vivo." target="_blank" rel="noopener noreferrer" className="w-full py-3 rounded-xl bg-green-500 hover:bg-green-600 text-white font-black text-xs uppercase flex items-center justify-center gap-2 transition-all shadow-sm mt-4">                Consultar Whats              </a>            </div>`;

const card2New = `{/* 2. Transmissão ao vivo */}            <div className="p-6 rounded-2xl bg-gray-50 border border-gray-200 shadow-xl flex flex-col justify-between">              <div>                <h3 className="text-lg font-black text-black uppercase tracking-tight mb-2">Transmissão ao Vivo</h3>                <p className="text-black text-sm mb-4 font-medium">Estrutura de streaming para seu evento ou podcast.</p>                <div className="text-xl font-black text-black font-mono mb-4">R$ 150 <span className="text-xs font-bold">/ hora</span></div>              </div>              <a href="https://pay.kiwify.com.br/elj3ZQY" target="_blank" rel="noopener noreferrer" className="w-full py-3 rounded-xl bg-gray-900 hover:bg-black text-white font-black text-xs uppercase flex items-center justify-center gap-2 transition-all shadow-sm mt-4 text-center">                COMPRAR TRANSMISSÃO AO VIVO              </a>            </div>`;

// 3. Stories tempo real: https://pay.kiwify.com.br/N51MmGe
const card3Old = `{/* 3. Stories tempo real */}            <div className="p-6 rounded-2xl bg-gray-50 border border-gray-200 shadow-xl flex flex-col justify-between">              <div>                <h3 className="text-lg font-black text-black uppercase tracking-tight mb-2">Stories Tempo Real</h3>                <p className="text-black text-sm mb-4 font-medium">Cobertura dinâmica para suas redes sociais.</p>              </div>              <a href="https://wa.me/5549991052315?text=Ol%C3%A1%21%20Gostaria%20de%20saber%20mais%20sobre%20Stories%20Tempo%20Real." target="_blank" rel="noopener noreferrer" className="w-full py-3 rounded-xl bg-green-500 hover:bg-green-600 text-white font-black text-xs uppercase flex items-center justify-center gap-2 transition-all shadow-sm mt-4">                Consultar Whats              </a>            </div>`;

const card3New = `{/* 3. Stories tempo real */}            <div className="p-6 rounded-2xl bg-gray-50 border border-gray-200 shadow-xl flex flex-col justify-between">              <div>                <h3 className="text-lg font-black text-black uppercase tracking-tight mb-2">Stories Tempo Real</h3>                <p className="text-black text-sm mb-4 font-medium">Cobertura dinâmica para suas redes sociais.</p>                <div className="text-xl font-black text-black font-mono mb-4">R$ 150 <span className="text-xs font-bold">/ hora</span></div>              </div>              <a href="https://pay.kiwify.com.br/N51MmGe" target="_blank" rel="noopener noreferrer" className="w-full py-3 rounded-xl bg-gray-900 hover:bg-black text-white font-black text-xs uppercase flex items-center justify-center gap-2 transition-all shadow-sm mt-4 text-center">                COMPRAR STORIES TEMPO REAL              </a>            </div>`;

// 4. Arte divulgação
const card4Old = `{/* 4. Arte divulgação */}            <div className="p-6 rounded-2xl bg-gray-50 border border-gray-200 shadow-xl flex flex-col justify-between">              <div>                <h3 className="text-lg font-black text-black uppercase tracking-tight mb-2">Arte Divulgação</h3>                <p className="text-black text-sm mb-4 font-medium">Design profissional e criativos de alta conversão.</p>              </div>              <a href="https://wa.me/5549991052315?text=Ol%C3%A1%21%20Gostaria%20de%20saber%20mais%20sobre%20Arte%20Divulga%C3%A7%C3%A3o." target="_blank" rel="noopener noreferrer" className="w-full py-3 rounded-xl bg-green-500 hover:bg-green-600 text-white font-black text-xs uppercase flex items-center justify-center gap-2 transition-all shadow-sm mt-4">                Consultar Whats              </a>            </div>`;

const card4New = `{/* 4. Arte divulgação */}            <div className="p-6 rounded-2xl bg-gray-50 border border-gray-200 shadow-xl flex flex-col justify-between">              <div>                <h3 className="text-lg font-black text-black uppercase tracking-tight mb-2">Arte Divulgação</h3>                <p className="text-black text-sm mb-4 font-medium">Design profissional e criativos de alta conversão.</p>                <div className="text-xl font-black text-black font-mono mb-4">R$ 100 <span className="text-xs font-bold">/ arte</span></div>              </div>              <a href="https://wa.me/5549991052315?text=Ol%C3%A1%21%20Gostaria%20de%20contratar%20a%20Arte%20de%20Divulga%C3%A7%C3%A3o%20por%20R%24100." target="_blank" rel="noopener noreferrer" className="w-full py-3 rounded-xl bg-gray-900 hover:bg-black text-white font-black text-xs uppercase flex items-center justify-center gap-2 transition-all shadow-sm mt-4 text-center">                COMPRAR ARTE DIVULGAÇÃO (R$ 100)              </a>            </div>`;

content = content.replace(card2Old, card2New);
content = content.replace(card3Old, card3New);
content = content.replace(card4Old, card4New);

fs.writeFileSync('src/SalesPage.tsx', content);
console.log("Updated cards successfully");
